version: 2

project_name: recomphamr

before:
  hooks:
    - go mod tidy

builds:
  - id: recomphamr
    main: ./cmd/recomphamr
    binary: recomphamr
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath

archives:
  - id: recomphamr
    builds:
      - recomphamr
    name_template: "recomphamr_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "SHA256SUMS"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  disable: true
